### ISSUE TITLE
Optional TU-Student verification

### ISSUE THREAD

**Issue by meepoSenpai** [fsr/course-management#10]
In case of student-only events/courses students should be able to verify that they are in fact students (since non-students should be able to register as well)

**Comment by JustusAdam** [comment]
Functionality implemented as of fd7b76ed8591bdcfbf04fb8241db80f40162f6e9 (untested)

**Comment by manuelthieme** [comment]
When registering as a non student and then trying to do this later, there is an "IntegrityError at /accounts/verify/student/"
