### ISSUE TITLE
Clean permissions

### ISSUE THREAD

**Issue by JustusAdam** [fsr/course-management#19]
Certain subsystems still require proper clean permission management.

- Courses 
    - [x] Each course needs to have its own edit/delete permissions
    - [x] Permissions need to be automatically assigned during creation
- Polls
    - [x] Each poll requires its own edit/delete permissions
    - [x] Permissions need to be automatically assigned during creation

**Comment by Lodifice** [comment]
Everything that can be modelled by permissions is done, validating tokens is part of #20.
