### ISSUE TITLE
Combat Missing Unicode Support On Linux

### ISSUE THREAD

**Issue by pbfman** [fsr/course-management#30]
With Linux I can't see the icons eg. behind "report bugs [] and errors []" and so on whether in firefox, chrome or opera.
Windows+Firefox displayed the icons but maybe its just an unreproducible fault on my system.

Linux Mint 13 (Ubuntu 12.04)
Mentioned browsers latest version

**Comment by kiliankoe** [comment]
Seem to be standard emoji chars present in Unicode. Unfortunately emoji support is still rather *meh* across systems and browsers, but I suggest leaving it as is.

**Comment by manuelthieme** [comment]
The Corporate Design provides using fontawesome icons. This will be the way is is gonna fixed... some day.

**Comment by pbfman** [comment]
Sounds good. Just an optical issue.

**Comment by JustusAdam** [comment]
Since this has come up as an issue I think it is a good idea to just leave this open until the new icons are in.
