### ISSUE TITLE
New vendor code handling

### ISSUE THREAD

**Issue by JustusAdam** [fsr/course-management#4]
I have removed the vendor code (jQuery, bootstrap) from the repo. 

Instead I have added an install script which downloads those resources automatically into `src/static/vendor`. 

So next time you `git pull` you may have to run `install.sh` to get bootstrap and jQuery. @manuelthieme @Feliix42 @Lodifice @lucasvog 

I also added the `vendor` directory to the `.gitignore` which means you should have no trouble with accidentally checking all the vendor code into git again.

**Comment by sebschrader** [comment]
What about using a package manager, like bower, instead of rolling your own?

**Comment by JustusAdam** [comment]
Sure, thats a possibility. But there are several reasons I don't do that:

1. I don't know bower (well enough)
2. Not everyone has bower installed, but pretty much everyone has `curl` and `rsync`
3. It seems a bit overkill for only 2 dependencies. All python dependencies are already handled via pip.

**Comment by JustusAdam** [comment]
All right, I initialised bower. Now how do I like the files? By including `static/vendor/bootstrap/dist/js/<something>.js` or is there a cleaner way?

**Comment by kiliankoe** [comment]
Bower is currently dying (or close to it), just fyi. https://github.com/bower/bower/pull/1748

**Comment by JustusAdam** [comment]
I don't think that'll happen. Bower is much too big to just die.

**Comment by JustusAdam** [comment]
Closed with #6
