### ISSUE TITLE
How to join if you are not a student anymore?

### ISSUE THREAD

**Issue by fer-rum** [fsr/course-management#41]
Persons, who want to teach but do no longer have an s-number, can not join since the s-number is always required.

Suggestion for improvement: Introduce an "No student" checkbox that acts as an alternative. Of course crediting then is impossible.

**Comment by manuelthieme** [comment]
actually the s-number is not required. You may leave it blank.
The "no student" checkbox is in fact an idea we had before but somehow we did not implement it.

**Comment by fer-rum** [comment]
Negative. If I leave it blank it rejects me, stating that the s-number is required.

**Comment by JustusAdam** [comment]
I think you may have to leave the faculty empty as well if you're not enrolling as a student.

**Comment by Feliix42** [comment]
Yes, that's it. You have to leave the faculty blank if you're not a student. I think this needs to be made much more clear for the user.

**Comment by fer-rum** [comment]
This is not useful. If you are a faculty staff member you have not have an s-number any more, but are indeed associated with a faculty.

**Comment by dirkonet** [comment]
This is not necessarily true. If you have an sNumber, you will retain it when you become a staff member. As I already mentioned elsewhere: having an sNumber does not imply being a student, being a student does not imply having an sNumber.

**Comment by Feliix42** [comment]
But how should we verify that you are _really_ a faculty staff member? We could of course accept any @tu-dresden.de mail address, that would solve the problem.

**Comment by kiliankoe** [comment]
Obviously the CM is going to need IDM integration... *duckundweg*

**Comment by dirkonet** [comment]
Is there any reason why we need to verify students/staff members? "Affiliated with TU Dresden" can be strongly hinted at (not necessarily proven) by having a tu-dresden.de email address or ZIH login if we for some reason want to exclude non-TU members. IDM integration would give us staff or student status, but why would we need it?
