### ISSUE TITLE
Yay, markdown. But which one?

### ISSUE THREAD

**Issue by fer-rum** [fsr/course-management#44]
It is nice that you can use markdown for the course description. Question is: which one of the dozens of dialects?

Please add a link to a cheat sheet for the appropriate markdown.

**Comment by JustusAdam** [comment]
It's the pure original.

**Comment by fer-rum** [comment]
It nevertheless seems to ignore all attempts to start a new paragraph or insert HTML-tags.

**Comment by JustusAdam** [comment]
That's because most HTML tags are being sanitized. It has nothing to do with the markdown. It may be that I forgot to allow `<p>` or `<br />` tags.

**Comment by JustusAdam** [comment]
If you need other HTML tags you can open an issue for them and we can debate enabling them.

**Comment by pbfman** [comment]
<p> and <br /> are removed.
Have the same problem to properly format the description. Just want some line breaks but nothing seems to work...
In addition links are displayed white which is probably not a good choice because of the white background.

**Comment by Feliix42** [comment]
I readjusted the **bleach** module in commit b1efc99. `<p>` and `<br />` are now in the list of allowed tags.
