### ISSUE TITLE
ZIH login instead of "S number"

### ISSUE THREAD

**Issue by dirkonet** [fsr/course-management#45]
Not every student has an "S number". The wording should be changed to "ZIH login", "ZIH login name" or similar.

**Comment by h4llow3En** [comment]
@dirkonet maybe you could work on this issue

**Comment by dirkonet** [comment]
In the time I'd need to even find and understand where to change this, someone more familiar with the project could already have done it twice ⏳

**Comment by h4llow3En** [comment]
But no one of us knows how to authenticate with the ZIH

**Comment by dirkonet** [comment]
This knowledge is not necessary to just change all occurences of "S number" or similar to "ZIH login" or similar.

**Comment by sjaster** [comment]
I don't see the point on changing the it to ZIH-Login. The student verification works with the s-number. Change it to the ZIH-Login on the registration page could cause the problem that people enter the full mail adress.
