### ISSUE TITLE
Translations Incomplete On Course Overview

### ISSUE THREAD

**Issue by hannesweisbach** [fsr/course-management#47]
I'm viewing this page: https://www.ifsr.de/kurse/course/8/
Under 'Status' it says: 'This course is currently Aktiv.', when it should say 'This course is currently active.'.
Whatever an 'active' course is. I guess it's not passive. (scnr)

**Comment by JustusAdam** [comment]
Are you viewing the site in german?

**Comment by hannesweisbach** [comment]
Well. The Accept-Language header is  'de-de'. The page itself contains only english text. Therefore, I assumed the page is not localised and reported this bug. If you do honour the Accept-Language header then I'd like to change my bug report to:
1) German localisation is missing
2) If you can't localise the entire page, localise nothing.

**Comment by JustusAdam** [comment]
I think the localisation is already in, but not everything, by which I mean very little, has been translated yet.

**Comment by Feliix42** [comment]
So I'm guessing this goes with #25?

**Comment by h4llow3En** [comment]
fixed in f231f02
