### ISSUE TITLE
Course Schedule Is Ambiguous

### ISSUE THREAD

**Issue by hannesweisbach** [fsr/course-management#48]
I'm viewing page https://www.ifsr.de/kurse/course/8/ (C - Advanced course)

Under the point 'Schedule' it says "<bullet-point> Thursdays, 2nd - APB/E067".

1) APB/E067 is a location and not part of a schedule. Either call it "When & Where" (instead of Schedule) or add a point Location/Room

2) I still don't know when the course is. 'Thursdays, 2nd' could mean:
- every 2nd Thursday in a month
- Thursdays every 2nd week
- Thursdays every 2nd month
- every Thursday from 9:20 to 10:50
- Thursday, June 2nd

Also, remove the bullet point - no other entry has one. Somehow the font is also different for this one entry.

**Comment by JustusAdam** [comment]
1. A schedule may very well contain a location, especially if, like in this case, the location is tied to the date.
1. the "2nd" refers to the second double period. Nothing else makes sense. But I think it may be a good idea to make that more apparent.
1. Font and bullet point are WIP
