### ISSUE TITLE
User Accounts Can't Be Deleted

### ISSUE THREAD

**Issue by Feliix42** [fsr/course-management#51]
There is no option for a user to delete his account.

**Comment by JustusAdam** [comment]
I am not sure we want to allow outright deletion, but we may want to allow them to disable it.

**Comment by kiliankoe** [comment]
It's a good practice to *always* give users the option of deleting everything pertaining to their accounts.

**Comment by JustusAdam** [comment]
I am not sure that's true. I'd like to be able to retain some information in case of abuse.

**Comment by dirkonet** [comment]
Please note that we do have to fill out https://www.stura.tu-dresden.de/webfm_send/1934 anyways and have it approved by the Datenschutzbeauftragter of either the StuRa or the University. @JustusAdam can argue with them ;)

**Comment by Feliix42** [comment]
Implemented with #85
