### ISSUE TITLE
Description is not shown for admins

### ISSUE THREAD

**Issue by h4llow3En** [fsr/course-management#54]
Course descriptions are not shown if you have the role superuser, just 'Create new course', 'Edit' and 'Delete'

Should this be that way?

**Comment by Feliix42** [comment]
I can't reproduce this, course descriptions work just fine for me (tested with the [Assembler course](https://www.ifsr.de/kurse/subject/Assembler/)). Maybe this has been fixed already?

**Comment by h4llow3En** [comment]
I think this one is fixed.

**Comment by Feliix42** [comment]
Nice
