### ISSUE TITLE
Setting Course as "student only" has no effect

### ISSUE THREAD

**Issue by Feliix42** [fsr/course-management#62]
Although you can set a course as "student only" this has no effect on the ability of all users to enroll for these courses.

**Comment by Feliix42** [comment]
I'm thinking... Should `student only` courses only be visible to logged in users who are students? Or to everyone?

**Comment by h4llow3En** [comment]
It is probably the best, if those courses are only shown to students. Because they are also only announced to students anyway.

**Comment by reschl** [comment]
Should be visible to everyone. Not every student has an account. However, it should be visible that only students are allowed to participate.  `students only` should be enforced when a logged in user tries to enroll.

**Comment by Feliix42** [comment]
That's what I was about to type. :D

I'm currently working on the issue.

**Comment by Feliix42** [comment]
In 1ec2734 I added optical hints like this one:
<img width="455" alt="bildschirmfoto 2016-09-25 um 18 00 10" src="https://cloud.githubusercontent.com/assets/9332912/18816425/0fd124d6-834a-11e6-810b-f3e8b833383b.png">

No-Students now no longer can enroll for `student only` courses, the _enroll_ button is hidden. Already enrolled users can still drop out of the course but not re-enroll again.
