### ISSUE TITLE
Course administration problems

### ISSUE THREAD

**Issue by chlewe** [fsr/course-management#67]
There have been a few changes to the course administration recently that I think made it worse. They could very well be bugs:
- Course teachers without any additional permissions can add / remove teachers from their course.
- Course teachers are no longer able to remove students from their course.
## 

Here is a screenshot of what the website looks like to me: https://lewelup.me/public/screenshot_ifsrDeKurse.png

**Comment by Feliix42** [comment]
Every teacher _should_ be able to remove a student from their course although the way to reach this option is very very unintuitive:

You have to click on the `xx of yy` label to reach the enrollment overview.

Can you please check if you're able to reach this page? :)

**Comment by chlewe** [comment]
That works just fine; thank you for your help.

This _secret_ button is indeed a problem: If you don't know (or forget, like in my case) that it exists, you will never, ever find it, but I assume that a visible button is already planned, so I won't suggest the obvious.
