### ISSUE TITLE
Brainstorming: New Deployment

### ISSUE THREAD

**Issue by Feliix42** [fsr/course-management#68]
The deployment right now is way too complicated and the `grunt install` command ist completely broken. So @h4llow3En and I think that we should take a new approach on this:

The `Gruntfile.coffee` should be repaired and fixed appropriately so that it becomes finally usable again. Then, the deployment should be simplified in a way, that after every tagged release in `master`, _Travis_ then builds the course-management, ready for deploy and pushes it to the __deploy__-branch (to avoid the `node`-`bower`-`grunt`-mess on our server). This branch can then be pulled to our server and everything is ready.

_This is just the result of a short brainstorming we did, feedback and other ideas are very much welcome! The overhead of this method may be a bit too large, I know._

**Comment by JustusAdam** [comment]
Originally the idea was (i remember now) to have something like a `grunt package` command, which, after building and installing bundles all compiled files, and only the necessary ones, into an archive which we could then drop on the server. 
I think something like that would still be necessary with what you're proposing.
