### ISSUE TITLE
Can't register when "mobile" (Faculty field issue)

### ISSUE THREAD

**Issue by evilham** [fsr/course-management#69]
When using a mobile browser (tested chrome + firefox on android), it's not possible to pick a faculty and therefore not possible to register.

Selecting "Show desktop version" on firefox and refreshing the site fixes the dropdown and with it the register process.

If the dropdown options are loaded via ajax, it could be an issue with unreliable network connections.

**Comment by JustusAdam** [comment]
How exactly is is "not possible to pick a faculty"? Is the field not showing up or the drop-down does not work?

**Comment by evilham** [comment]
The dropdown renders "-----" and does not react to touch events.
Loading https://www.ifsr.de/kurse/accounts/register/ with chrome, and activating the device toolbar under developer tools trivially demonstrates the issue.
Using the inspector shows that the `select` HTML node actually contains all the `options`, it just does not dropdown with touch events, therefore it's impossible to use with any touch device.

**Comment by Feliix42** [comment]
#91 removed the Faculty picker altogether so this is obsolete.
