### ISSUE TITLE
Links on a public profile are rendered in white (on white background)

### ISSUE THREAD

**Issue by JustusAdam** [fsr/course-management#71]
I think it is already evident from the title that this makes the links completely unreadable.

![screen shot 2017-04-04 at 9 10 13 pm](https://cloud.githubusercontent.com/assets/5824532/24674346/5e37943a-197b-11e7-8973-78d3d740900e.png)

**Comment by sjaster** [comment]
This seems to be fixed.

![screenshot-2017-10-13 sebastian jaster course manager - beta](https://user-images.githubusercontent.com/23065142/31567464-e8a26308-b06f-11e7-9977-8771607dec7d.png)
